services:
  app:
    build: .
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - AB_BASE_URL=${AB_BASE_URL?}
      - AB_CLIENT_ID=${AB_CLIENT_ID?}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET?}
      - AB_NAMESPACE=${AB_NAMESPACE?}
      - ITEM_ID_TO_GRANT=${ITEM_ID_TO_GRANT?}
      - LOKI_URL=http://host.docker.internal:3100/loki/api/v1/push
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=ExtendEventHandlerServerPython
      - GRPC_VERBOSITY=debug
    extra_hosts:
      - host.docker.internal:host-gateway
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://host.docker.internal:3100/loki/api/v1/push
    #     mode: non-blocking
    #     max-buffer-size: 4m
    #     loki-retries: "3"
