# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_pb2 as client__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientClientCreatedServiceStub(object):
    """--- service ---

    Publishes a ClientCreated to the Client channel. (oneOf variant) (client ClientCreated)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientClientCreatedService/OnMessage',
                request_serializer=client__pb2.ClientCreated.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientClientCreatedServiceServicer(object):
    """--- service ---

    Publishes a ClientCreated to the Client channel. (oneOf variant) (client ClientCreated)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientClientCreatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientCreated.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientClientCreatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientClientCreatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientClientCreatedService(object):
    """--- service ---

    Publishes a ClientCreated to the Client channel. (oneOf variant) (client ClientCreated)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientClientCreatedService/OnMessage',
            client__pb2.ClientCreated.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientClientDeletedServiceStub(object):
    """Publishes a ClientDeleted to the Client channel. (oneOf variant) (client ClientDeleted)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientClientDeletedService/OnMessage',
                request_serializer=client__pb2.ClientDeleted.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientClientDeletedServiceServicer(object):
    """Publishes a ClientDeleted to the Client channel. (oneOf variant) (client ClientDeleted)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientClientDeletedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientDeleted.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientClientDeletedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientClientDeletedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientClientDeletedService(object):
    """Publishes a ClientDeleted to the Client channel. (oneOf variant) (client ClientDeleted)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientClientDeletedService/OnMessage',
            client__pb2.ClientDeleted.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientClientUpdatedServiceStub(object):
    """Publishes a ClientUpdated to the Client channel. (oneOf variant) (client ClientUpdated)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientClientUpdatedService/OnMessage',
                request_serializer=client__pb2.ClientUpdated.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientClientUpdatedServiceServicer(object):
    """Publishes a ClientUpdated to the Client channel. (oneOf variant) (client ClientUpdated)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientClientUpdatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientUpdated.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientClientUpdatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientClientUpdatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientClientUpdatedService(object):
    """Publishes a ClientUpdated to the Client channel. (oneOf variant) (client ClientUpdated)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientClientUpdatedService/OnMessage',
            client__pb2.ClientUpdated.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientThirdPartyClientThirdPartyCreatedServiceStub(object):
    """Publishes a ClientThirdPartyCreated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyCreated)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyCreatedService/OnMessage',
                request_serializer=client__pb2.ClientThirdPartyCreated.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientThirdPartyClientThirdPartyCreatedServiceServicer(object):
    """Publishes a ClientThirdPartyCreated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyCreated)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientThirdPartyClientThirdPartyCreatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientThirdPartyCreated.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyCreatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyCreatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientThirdPartyClientThirdPartyCreatedService(object):
    """Publishes a ClientThirdPartyCreated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyCreated)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyCreatedService/OnMessage',
            client__pb2.ClientThirdPartyCreated.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientThirdPartyClientThirdPartyDeletedServiceStub(object):
    """Publishes a ClientThirdPartyDeleted to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyDeleted)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyDeletedService/OnMessage',
                request_serializer=client__pb2.ClientThirdPartyDeleted.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientThirdPartyClientThirdPartyDeletedServiceServicer(object):
    """Publishes a ClientThirdPartyDeleted to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyDeleted)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientThirdPartyClientThirdPartyDeletedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientThirdPartyDeleted.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyDeletedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyDeletedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientThirdPartyClientThirdPartyDeletedService(object):
    """Publishes a ClientThirdPartyDeleted to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyDeleted)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyDeletedService/OnMessage',
            client__pb2.ClientThirdPartyDeleted.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientThirdPartyClientThirdPartyUpdatedServiceStub(object):
    """Publishes a ClientThirdPartyUpdated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyUpdated)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyUpdatedService/OnMessage',
                request_serializer=client__pb2.ClientThirdPartyUpdated.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientThirdPartyClientThirdPartyUpdatedServiceServicer(object):
    """Publishes a ClientThirdPartyUpdated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyUpdated)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientThirdPartyClientThirdPartyUpdatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientThirdPartyUpdated.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyUpdatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyUpdatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientThirdPartyClientThirdPartyUpdatedService(object):
    """Publishes a ClientThirdPartyUpdated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyUpdated)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyUpdatedService/OnMessage',
            client__pb2.ClientThirdPartyUpdated.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientPermissionsClientPermissionsCreatedServiceStub(object):
    """Publishes a ClientPermissionCreated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsCreated)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsCreatedService/OnMessage',
                request_serializer=client__pb2.ClientPermissionCreated.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientPermissionsClientPermissionsCreatedServiceServicer(object):
    """Publishes a ClientPermissionCreated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsCreated)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientPermissionsClientPermissionsCreatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientPermissionCreated.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientPermissionsClientPermissionsCreatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientPermissionsClientPermissionsCreatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientPermissionsClientPermissionsCreatedService(object):
    """Publishes a ClientPermissionCreated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsCreated)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsCreatedService/OnMessage',
            client__pb2.ClientPermissionCreated.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientPermissionsClientPermissionsDeletedServiceStub(object):
    """Publishes a ClientPermissionDeleted to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsDeleted)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsDeletedService/OnMessage',
                request_serializer=client__pb2.ClientPermissionDeleted.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientPermissionsClientPermissionsDeletedServiceServicer(object):
    """Publishes a ClientPermissionDeleted to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsDeleted)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientPermissionsClientPermissionsDeletedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientPermissionDeleted.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientPermissionsClientPermissionsDeletedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientPermissionsClientPermissionsDeletedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientPermissionsClientPermissionsDeletedService(object):
    """Publishes a ClientPermissionDeleted to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsDeleted)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsDeletedService/OnMessage',
            client__pb2.ClientPermissionDeleted.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientPermissionsClientPermissionsUpdatedServiceStub(object):
    """Publishes a ClientPermissionUpdated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsUpdated)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnMessage = channel.unary_unary(
                '/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsUpdatedService/OnMessage',
                request_serializer=client__pb2.ClientPermissionUpdated.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ClientPermissionsClientPermissionsUpdatedServiceServicer(object):
    """Publishes a ClientPermissionUpdated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsUpdated)
    """

    def OnMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientPermissionsClientPermissionsUpdatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=client__pb2.ClientPermissionUpdated.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.iam.client.v1.ClientPermissionsClientPermissionsUpdatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.iam.client.v1.ClientPermissionsClientPermissionsUpdatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientPermissionsClientPermissionsUpdatedService(object):
    """Publishes a ClientPermissionUpdated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsUpdated)
    """

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsUpdatedService/OnMessage',
            client__pb2.ClientPermissionUpdated.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
